### ISSUE TITLE
Packages don't install to python3 library

### ISSUE THREAD

**Issue by J-Massey** [b-fg/postproc#1]
When following the instructions, `sudo pip3 install -e .` installs to the pwd and not into the python libraries. How can I rectify this?

**Comment by b-fg** [comment]
Those instructions where a bit old and I now recommend using a virtual envoriment such as Conda. Please check the updated README.md in 863845fdd016838424e12b969483c8516201eba8.

**Comment by b-fg** [comment]
Also, in the old guidelines, `sudo pip3 install -e .` should be run in the package directory (in case you were not doing so).
